version: '3.4'

services:

  server:
    image: "sample_app:latest"
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: builders/docker/Dockerfile
    entrypoint: ["./server"]
    env_file:
      - ./builders/docker/.env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - postgres

  postgres:
    image: "postgres:15-alpine"
    #restart: always
    container_name: ${DB_HOST}
    healthcheck:
      test: pg_isready -U ${DB_USER}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    expose:
      - "5432"

#  redis:
#    image: 'redis:7.0'
#    restart: always
#    ports:
#      - "6379:6379"
#      - ${CACHE_PORT}:6379
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
