version: '3.4'

services:

  server:
    container_name: ${APP_NAME}
    image: "sample_app:latest"
    build:
      context: .
      dockerfile: builders/docker/Dockerfile
    entrypoint: ["./server"]
    env_file:
      - ./builders/docker/.env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: database
    image: "postgres:15-alpine"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3000M
    healthcheck:
      test: pg_isready -U ${DB_USER}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    expose:
      - "5432"

  redis:
    container_name: redis
    image: "redis:7.0.5"
    ports:
      - ${CACHE_PORT}:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
