### Check liveness response
GET http://localhost:{{http_port}}/api/v1/items/liveness

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Check metrics response
GET http://localhost:{{http_port}}/api/v1/items/metrics

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Check databases response
GET http://localhost:{{http_port}}/api/v1/items/databases

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("Response content-type is json", function() {
  var type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
});

client.test("Headers option exists", function() {
  client.assert(response.body.hasOwnProperty("data"), "Cannot find 'data' option in response");
});
%}

### Check health response
GET http://localhost:{{http_port}}/api/v1/items/health

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Check create item response
POST http://localhost:{{http_port}}/api/v1/items

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}


### Check get item response
GET http://localhost:{{http_port}}/api/v1/items/1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Check update item response
PUT http://localhost:{{http_port}}/api/v1/items/1
Content-Type: application/json

{"start_time": "1", "finish_time": "1", "status": "DELETED"}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
