### Check liveness response
GET http://localhost:{{http_port}}/api/v1/sample/liveness

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Check metrics response
GET http://localhost:{{http_port}}/api/v1/sample/metrics

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Check databases response
GET http://localhost:{{http_port}}/api/v1/sample/databases

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("Response content-type is json", function() {
  var type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
});

client.test("Headers option exists", function() {
  client.assert(response.body.hasOwnProperty("data"), "Cannot find 'data' option in response");
});
%}


### Check health response
GET http://localhost:{{http_port}}/api/v1/sample/health

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
