name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  static-check:
    name: Code static check
    runs-on: ubuntu-latest
    steps:
      - name: Check out directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: lint
        uses: golangci/golangci-lint-action@v2

  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
